name: hospital_management_system
description: A hospital room management system
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # any normal dependencies

dev_dependencies:
  test: ^1.25.0
  mocktail: ^0.3.0
